export type Article = {
  slug: string
  title: string
  excerpt: string
  author: 'Adam Raymond Belda' | 'Renz Gutierrez Belda' | 'Adam Belda + Renz Belda'
  authorRole: string
  category: string
  categorySlug: string
  keyword: string
  wordCount: string
  experienceBasis: string
  readTime: number
}

export const businessGuides: Article[] = [
  {
    slug: 'hipaa-client-onboarding-system',
    title: 'How to Design a Client Onboarding System That Is ISO and HIPAA Compliant From Day One',
    excerpt: 'The exact 4-layer compliance framework Adam built at MEDVA/Deel PH — reducing staff time-to-productivity from 4.5 days to under 6 hours while passing a HIPAA compliance review with zero access-control findings.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'HIPAA compliant onboarding system Philippines',
    wordCount: '1,400–1,800',
    experienceBasis: 'MEDVA / Deel PH, Sept 2024 – Jan 2026',
    readTime: 8,
  },
  {
    slug: 'remote-workforce-security-architecture',
    title: 'Building a Remote Workforce Security Architecture for a Distributed Team',
    excerpt: 'The BYOD security architecture Adam deployed at NXTGEN Industries Melbourne — Azure AD Conditional Access, WireGuard VPN, Intune MDM, and the VPN kill-switch failure that led to a better design.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'remote workforce security architecture Philippines',
    wordCount: '1,400–1,800',
    experienceBasis: 'NXTGEN Industries Melbourne, Nov 2022 – Jul 2024',
    readTime: 9,
  },
  {
    slug: 'crm-revenue-operations-without-sales-team',
    title: 'How to Set Up a Revenue Operations System Using a CRM Without a Sales Team',
    excerpt: 'The 5-stage CRM pipeline and automation stack Adam configures for businesses that need pipeline visibility and follow-up discipline without a dedicated sales team — deployed across Salesforce, Zoho, and ClickUp.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'CRM revenue operations setup Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'Multiple CRM deployments across enterprise and SMB environments',
    readTime: 7,
  },
  {
    slug: 'sla-design-it-support-teams',
    title: 'SLA Design for IT Support Teams: How to Build Service Levels That Actually Hold',
    excerpt: 'The P1–P4 tiering framework and measurement stack Adam built at Emapta Philippines — including biweekly stakeholder sync meetings that became the company standard across 6 client accounts.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'IT support SLA design Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'Emapta Philippines Inc., Nov 2021 – Nov 2022',
    readTime: 7,
  },
  {
    slug: 'project-scoping-stop-scope-creep',
    title: 'Project Scoping for IT and Business Engagements: How to Stop Scope Creep Before It Starts',
    excerpt: 'What a scope document must actually contain, how the 2-week SPRINT structure prevents expectation drift, and why scope creep is almost always a scoping failure — not a client failure. From Adam\'s PMP and Scrum Master experience.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'IT project scoping scope creep prevention',
    wordCount: '1,200–1,600',
    experienceBasis: 'PMP + Scrum Master certified. SAP Philippines and Emapta SPRINT facilitation.',
    readTime: 7,
  },
  {
    slug: 'automate-client-reporting-without-analyst',
    title: 'How to Automate Your Client Reporting Without Hiring a Reports Analyst',
    excerpt: 'The 4-step automation stack Renz uses to eliminate manual weekly reporting — from Zendesk or JIRA data source through Google Sheets, Looker Studio, and scheduled Monday morning delivery.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'automated client reporting small business',
    wordCount: '1,000–1,400',
    experienceBasis: 'NXTGEN Industries and TaskUs reporting environments',
    readTime: 6,
  },
  {
    slug: 'it-onboarding-non-technical-staff',
    title: 'How to Design an IT Onboarding Process for Non-Technical New Hires',
    excerpt: 'The Day-Zero IT onboarding checklist Renz runs for every new client — M365 accounts and MFA configured before day one, password manager pre-populated, and a one-hour orientation call that eliminates 80% of first-week IT tickets.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'IT onboarding process non-technical staff',
    wordCount: '1,000–1,400',
    experienceBasis: 'NXTGEN Industries and GemuCube IT onboarding builds',
    readTime: 6,
  },
  {
    slug: 'business-process-mapping-lean-six-sigma',
    title: 'Business Process Mapping: How to Document What Your Business Actually Does',
    excerpt: 'The SIPOC methodology Adam applies using his Lean Six Sigma Black Belt certification — with a worked example, waste identification categories, and how each type of waste maps to an automation or elimination opportunity.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'business process mapping Lean Six Sigma Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'Lean Six Sigma Black Belt certification. Applied across enterprise environments.',
    readTime: 8,
  },
  {
    slug: 'startup-it-environment-without-it-team',
    title: 'How to Structure a Startup\'s IT Environment Without an In-House IT Team',
    excerpt: 'The 6-item baseline IT stack every 10-to-30-person business needs — and the most common audit finding across every GemuCube client engagement: a former employee with active access to company systems.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'startup IT environment setup Philippines',
    wordCount: '1,000–1,400',
    experienceBasis: 'GemuCube Solutions (2018–2021), NXTGEN Industries (2022–2024)',
    readTime: 6,
  },
  {
    slug: 'lead-generation-without-paid-ads',
    title: 'How to Build a Lead Generation System That Works Without Paid Advertising',
    excerpt: 'The 3-channel organic lead generation system Adam built for GemuCube — from 0 to 847 LinkedIn followers in 60 days, 6 discovery calls, and 1 signed retainer at zero ad spend. Every step documented.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Business Guides',
    categorySlug: 'business-guides',
    keyword: 'B2B lead generation without paid ads Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'GemuCube social media system. Top Tech Writer PH.',
    readTime: 7,
  },
]

export const techOpGuides: Article[] = [
  {
    slug: 'microsoft-365-setup-checklist-smb',
    title: 'Microsoft 365 Admin Center: The Setup Checklist Every SMB Should Run Before Onboarding Staff',
    excerpt: 'Four pre-onboarding steps Renz runs on every new M365 tenant — including why the Audit Log is off by default, why shared mailboxes should never be user accounts, and why SMS OTP is not a real second factor.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'Microsoft 365 setup checklist small business',
    wordCount: '1,200–1,600',
    experienceBasis: 'M365 Admin Center across NXTGEN Industries and GemuCube client environments',
    readTime: 8,
  },
  {
    slug: 'servicenow-vs-jira-vs-zendesk',
    title: 'ServiceNow vs. JIRA vs. Zendesk: Which Ticketing System Fits Your Business Stage',
    excerpt: 'An honest comparison from someone who has worked in all three — not a feature comparison, but a stage-appropriate recommendation based on real deployment experience at NXTGEN Industries and TaskUs.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'ServiceNow vs JIRA vs Zendesk comparison Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'ServiceNow (NXTGEN), JIRA (NXTGEN, TaskUs), Zendesk (GemuCube clients)',
    readTime: 7,
  },
  {
    slug: 'azure-conditional-access-plain-english',
    title: 'Azure Active Directory Conditional Access: A Plain-English Configuration Guide',
    excerpt: 'The three Conditional Access policies Renz deploys first on every Business Premium tenant — and the story of the client who deployed Enforce mode without testing and locked out their entire team at 8am Monday.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'Azure Conditional Access configuration guide Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'Azure AD Conditional Access at NXTGEN Industries and MEDVA environments',
    readTime: 8,
  },
  {
    slug: 'zapier-automation-stack-no-developer',
    title: 'How to Build a Zapier Automation Stack for a Business with No Developer',
    excerpt: 'The three automation patterns that cover 80% of business workflows — and the exact automation stack Renz built at NXTGEN Industries connecting JIRA, Slack, ClickUp, and the HR system.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'Zapier automation small business Philippines',
    wordCount: '1,000–1,400',
    experienceBasis: 'Zapier across NXTGEN Industries and GemuCube client environments',
    readTime: 6,
  },
  {
    slug: 'salesforce-vs-zoho-vs-clickup-crm',
    title: 'Salesforce vs. Zoho CRM vs. ClickUp: Choosing Your First CRM as a Growing Business',
    excerpt: 'Not a feature comparison — a practical stage-appropriate guide from someone who has configured all three in live environments. Includes the four things Adam configures on day one of any CRM deployment.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'Salesforce vs Zoho CRM comparison Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'Salesforce, Zoho, ClickUp, OrangeCRM, AgileCRM across multiple environments',
    readTime: 7,
  },
  {
    slug: 'wordpress-elementor-seo-without-agency',
    title: 'WordPress + Elementor Pro: How to Build a Business Website That Ranks Without an SEO Agency',
    excerpt: 'The exact technical stack and on-page SEO checklist Adam runs on every published page — across 7 properties built and ranked. SEO done in parallel with the build, not retrofitted after launch.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'WordPress Elementor Pro website SEO Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: '7 WordPress properties built (gemucube.com, nxtgenindustries.com.au, etc.)',
    readTime: 8,
  },
  {
    slug: 'google-analytics-4-weekly-reports',
    title: 'Google Analytics 4: The Five Reports Every Business Owner Should Review Weekly',
    excerpt: 'The five GA4 reports that give you actionable information — and how Adam configures conversion events via Google Tag Manager so the data is worth looking at in the first place.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'Google Analytics 4 reports small business',
    wordCount: '1,000–1,400',
    experienceBasis: 'GA4 implementation across multiple properties with conversion tracking',
    readTime: 6,
  },
  {
    slug: 'teamviewer-anydesk-rdp-security',
    title: 'Remote Desktop Support Without Compromising Security: TeamViewer, AnyDesk, and RDP Compared',
    excerpt: 'The specific security controls Renz applies to each remote access tool — and why RDP exposed directly to the internet is one of the most commonly exploited attack vectors in ransomware incidents.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'remote desktop support security TeamViewer AnyDesk Philippines',
    wordCount: '1,000–1,400',
    experienceBasis: 'TeamViewer, AnyDesk, LogMeIn, RDP across NXTGEN and GemuCube environments',
    readTime: 6,
  },
  {
    slug: 'it-incident-management-not-whatsapp',
    title: 'How to Build an IT Incident Management Process That Does Not Rely on WhatsApp',
    excerpt: 'Why WhatsApp IT support is a business risk — and the 4-step incident management process Renz implements to replace it with a system that has an audit trail, SLA measurement, and a knowledge base.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'IT incident management process small business',
    wordCount: '1,000–1,400',
    experienceBasis: 'ITSM deployment at NXTGEN Industries. Zoho Desk builds for GemuCube clients.',
    readTime: 6,
  },
  {
    slug: 'voip-configuration-remote-team',
    title: 'How to Configure VoIP Systems for a Remote or Hybrid Team: Avaya, Genesys, and Salesforce Phone',
    excerpt: 'The four most common VoIP configuration failures and the pre-go-live readiness checklist Renz runs before any VoIP system goes live — drawn from Avaya, Genesys Cloud, and Salesforce Phone experience.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Tech Operation Guides',
    categorySlug: 'tech-operation-guides',
    keyword: 'VoIP system configuration remote team Philippines',
    wordCount: '1,000–1,400',
    experienceBasis: 'Avaya, Genesys Cloud, Salesforce Built-in Phone across enterprise environments',
    readTime: 6,
  },
]

export const caseStudyArticles: Article[] = [
  {
    slug: 'medva-hipaa-onboarding-article',
    title: 'How We Built an ISO and HIPAA-Compliant Onboarding System for a U.S. Healthcare Staffing Platform',
    excerpt: 'From unencrypted email credentials and no audit trail to a 12-step compliant onboarding system — reducing time-to-productivity from 4.5 days to 6 hours and passing a HIPAA review with zero findings.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'HIPAA compliant onboarding system healthcare staffing',
    wordCount: '1,400–1,800',
    experienceBasis: 'MEDVA / Deel PH, Sept 2024 – Jan 2026',
    readTime: 9,
  },
  {
    slug: 'nxtgen-it-transformation-article',
    title: 'How We Transformed IT Operations for a Melbourne-Based Business in 90 Days',
    excerpt: 'Building a full IT operations function from zero — JIRA deployment, SLA framework, BYOD security, and a 47-article knowledge base that reduced onboarding support load by 60%. Both founders, 22 months.',
    author: 'Adam Belda + Renz Belda',
    authorRole: 'Co-Founders',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'IT operations transformation Philippines Australia',
    wordCount: '1,400–1,800',
    experienceBasis: 'NXTGEN Industries Melbourne, Nov 2022 – Jul 2024',
    readTime: 9,
  },
  {
    slug: 'sap-lms-stabilization-article',
    title: 'Inside the SAP Learning Management System: How We Stabilized an Enterprise Platform Nobody Could Fix',
    excerpt: 'SCORM validation from scratch, database integrity restoration for 340 learners, 14 deferred UI defects patched, and a SPRINT structure that reduced escalation queue age from 11 days to 3.2 days.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'SAP LMS technical support enterprise Philippines',
    wordCount: '1,400–1,800',
    experienceBasis: 'SAP Philippines, Jun 2020 – Oct 2021',
    readTime: 9,
  },
  {
    slug: 'emapta-sla-operations-article',
    title: 'From Reactive to Proactive: How We Built SLA Operations at Emapta Philippines',
    excerpt: 'Two SSL certificate expiry incidents in 6 months, no standard SLA report format, and an escalation queue with no named owners. How Adam fixed all three — and the report format that became the company standard.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'cloud application support SLA management Philippines',
    wordCount: '1,400–1,800',
    experienceBasis: 'Emapta Philippines Inc., Nov 2021 – Nov 2022',
    readTime: 8,
  },
  {
    slug: 'intelegencia-ai-annotation-article',
    title: 'How We Reduced AI Training Data Errors by 68% Using a Decision Tree and Spot-Check System',
    excerpt: 'Inter-annotator disagreement at 18%, full batches rejected by ML engineering, throughput pressure pushing speed over accuracy. Four systems Renz built that flipped all three metrics in 45 days.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'AI data annotation quality control Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'Intelegencia, 2021–2022',
    readTime: 7,
  },
  {
    slug: 'taskus-content-moderation-article',
    title: 'Scaling Content Moderation Quality at TaskUs: How Pre-Shift Calibration Changed Everything',
    excerpt: '45-minute calibration sessions that still didn\'t resolve disagreements. A decision reference log, category-level quality tracking, and pre-shift calibration checks that cut session time to 18 minutes.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'content moderation quality analysis process',
    wordCount: '1,000–1,400',
    experienceBasis: 'TaskUs Inc., 2024–2025',
    readTime: 6,
  },
  {
    slug: 'gemucube-website-portfolio-article',
    title: 'Building Seven Websites to a 90+ Lighthouse Score: The Technical Standard We Apply to Every Build',
    excerpt: 'Seven properties, one technical standard — Hello Elementor, RankMath Pro, WP Rocket, ShortPixel, Cloudflare, GA4 custom events. Every property at 90+ Lighthouse before launch, schema markup on every page type.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'WordPress website development 90 Lighthouse score Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'GemuCube internal website portfolio, 2018–Present',
    readTime: 7,
  },
  {
    slug: 'fractional-cto-startup-article',
    title: '90 Days as Fractional CTO: How We Eliminated PHP 48,000/Month in Wasted Tools and Built a Technology Roadmap',
    excerpt: 'Three overlapping subscription tools, two CRM platforms with no integration, no security baseline. The 90-day engagement that eliminated PHP 48,000/month in redundant subscriptions and produced a roadmap that went into Series A materials.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'fractional CTO Philippines startup technology audit',
    wordCount: '1,200–1,600',
    experienceBasis: 'GemuCube fractional CTO engagement methodology',
    readTime: 7,
  },
  {
    slug: 'zoho-crm-implementation-article',
    title: 'Zero to Pipeline Visibility in 3 Weeks: A Zoho CRM Implementation for a Philippines Professional Services Firm',
    excerpt: 'Two lost deals from missed follow-up. Two principals who disagreed on how many active deals were in the pipeline. Three weeks, one CRM, and the loss-reason data that changed how they qualified clients.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'Zoho CRM implementation Philippines professional services',
    wordCount: '1,200–1,600',
    experienceBasis: 'GemuCube project-based CRM engagement',
    readTime: 7,
  },
  {
    slug: 'it-support-infrastructure-article',
    title: 'From WhatsApp IT to a 74% First-Contact Resolution Rate: Building IT Support Infrastructure from Zero',
    excerpt: 'WhatsApp IT support → Zoho Desk with Slack integration → 74% first-contact resolution rate in 60 days. The Slack slash command that drove adoption, and the knowledge base that did most of the work.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Case Studies',
    categorySlug: 'case-studies',
    keyword: 'IT helpdesk setup small business Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'GemuCube retainer-based helpdesk engagement',
    readTime: 7,
  },
]

export const projectArticles: Article[] = [
  {
    slug: 'building-gemucube-com',
    title: 'Project Log: Building gemucube.com — Every Technical Decision, SEO Choice, and Lesson from Day One',
    excerpt: 'Why WordPress over no-code, the full technical stack, SEO in parallel with build, 90-day organic results — and three things Adam would do differently if building it again today.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'WordPress website build log SEO configuration',
    wordCount: '1,400–1,800',
    experienceBasis: 'GemuCube website build, 2024',
    readTime: 9,
  },
  {
    slug: 'jira-deployment-nxtgen',
    title: 'Project Log: Deploying JIRA Service Management for a 30-Person Cross-Border Team',
    excerpt: 'Week-by-week: assessment, configuration, and the rollout adoption failure that 60% of the team ignored — until a Slack slash command made the right path the easiest path.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'JIRA Service Management deployment guide',
    wordCount: '1,200–1,600',
    experienceBasis: 'NXTGEN Industries, Nov 2022 – Jul 2024',
    readTime: 7,
  },
  {
    slug: 'hipaa-controls-implementation',
    title: 'Project Log: Configuring ISO and HIPAA Controls for a U.S.-Facing Healthcare Business',
    excerpt: 'Month-by-month: audit, gap analysis (7 former employees with active accounts), control implementation sequence — and why documentation of a system that doesn\'t exist yet is speculation.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'HIPAA IT controls implementation sequence Philippines',
    wordCount: '1,400–1,800',
    experienceBasis: 'MEDVA / Deel PH, Sept 2024 – Jan 2026',
    readTime: 9,
  },
  {
    slug: 'gmail-to-google-workspace-10-days',
    title: 'Project Log: Migrating a 14-Person Business from Personal Gmail to Google Workspace in 10 Days',
    excerpt: 'Day-by-day: DNS configuration, GWMME migration, the hidden second personal accounts three team members didn\'t mention, and a Saturday morning training session that got the whole team live by Monday.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'Google Workspace migration personal Gmail Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'GemuCube Google Workspace migration engagement',
    readTime: 7,
  },
  {
    slug: 'it-support-portal-reduced-tier1-tickets',
    title: 'Project Log: Building a Self-Service IT Support Portal That Reduced Tier-1 Tickets by 67%',
    excerpt: '37% of all tickets were tier-1. A Zoho Desk portal with Azure SSPR, structured intake forms, and a 15-article knowledge base brought tier-1 volume from 67 to 22 per month in 60 days.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'IT support portal self-service helpdesk Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'GemuCube project-based helpdesk portal engagement',
    readTime: 7,
  },
  {
    slug: 'fractional-cto-first-90-days',
    title: 'Project Log: The First 90 Days of a Fractional IT Operations Director Engagement',
    excerpt: 'Days 1–14: listen and document. Days 15–45: top 5 security findings only. Days 46–90: build the systems and write the documentation the business can read without you. Then decide together what\'s next.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'fractional IT operations director engagement Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'GemuCube fractional IT operations director methodology',
    readTime: 7,
  },
  {
    slug: 'social-media-lead-generation-60-days',
    title: 'Project Log: Launching a Social Media Lead Generation System from Zero — 60-Day Results',
    excerpt: 'LinkedIn first — one platform done well before five platforms done poorly. 0 to 847 followers, 6 discovery calls, 1 signed retainer, PHP 0 ad spend. The content calendar, engagement protocol, and CRM connection that made it work.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'LinkedIn lead generation B2B Philippines',
    wordCount: '1,200–1,600',
    experienceBasis: 'GemuCube social media lead generation system, 2024',
    readTime: 7,
  },
  {
    slug: 'microsoft-365-tenant-setup-order',
    title: 'Project Log: Setting Up Microsoft 365 Business Premium from a New Tenant — In the Exact Order Renz Does It',
    excerpt: 'First 30 minutes: break-glass admin and security baseline. First hour: domain, SPF, DKIM, DMARC, and a user account template. Why Renz always deploys Conditional Access for Business Premium — never Security Defaults.',
    author: 'Renz Gutierrez Belda',
    authorRole: 'IT Support Specialist / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'Microsoft 365 Business Premium tenant setup guide',
    wordCount: '1,200–1,600',
    experienceBasis: 'M365 Admin Center across multiple client environments',
    readTime: 7,
  },
  {
    slug: 'website-architecture-design-professional-services',
    title: 'Project Log: Designing a Six-Page Website Architecture for a Professional Services Firm',
    excerpt: 'How to present a complex, multi-discipline service offering without losing the visitor in 10 seconds. The information architecture decisions, the headline test, and why the embedded partnership model anchors every page.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'website architecture design professional services firm',
    wordCount: '1,200–1,600',
    experienceBasis: 'gemucube.com architecture and content design',
    readTime: 7,
  },
  {
    slug: 'six-sigma-dmaic-it-support',
    title: 'Project Log: Running a Six Sigma DMAIC Sprint on an IT Support Operation — What We Found',
    excerpt: 'Define, Measure, Analyze, Improve, Control — applied to an IT support operation with an 11.4-day average ticket age and 28% recurrence rate. The root causes were not what anyone expected.',
    author: 'Adam Raymond Belda',
    authorRole: 'IT Operations Director / Co-Founder',
    category: 'Project Articles',
    categorySlug: 'project-articles',
    keyword: 'Lean Six Sigma DMAIC IT support process improvement',
    wordCount: '1,200–1,600',
    experienceBasis: 'Lean Six Sigma Black Belt. Applied at NXTGEN Industries.',
    readTime: 8,
  },
]

export const allArticles = [
  ...businessGuides,
  ...techOpGuides,
  ...caseStudyArticles,
  ...projectArticles,
]

export const categories = [
  { label: 'Business Guides', slug: 'business-guides', count: businessGuides.length, description: 'Practical, experience-grounded guides for founders and business operators.' },
  { label: 'Tech Operation Guides', slug: 'tech-operation-guides', count: techOpGuides.length, description: 'Hands-on technical guides drawn from real enterprise deployments.' },
  { label: 'Case Studies', slug: 'case-studies', count: caseStudyArticles.length, description: 'Real clients, real challenges, real outcomes — no anonymized generics.' },
  { label: 'Project Articles', slug: 'project-articles', count: projectArticles.length, description: 'Behind-the-scenes project logs from real GemuCube engagements.' },
]
